version: '3.9'

name: fanflix

services:
  api:
    image: ${DOCKERHUB_USERNAME}/fanflix-api:latest
    container_name: fanflix_api
    restart: unless-stopped
    networks:
      - traefik-global-proxy
    environment:
      DATABASE_USER_NAME: ${DATABASE_USER_NAME}
      DATABASE_HOST_NAME: ${DATABASE_HOST_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_LINK: ${DATABASE_LINK}
      API_SECRET: ${API_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION} 
      NODE_ENV: production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.simple-fe.rule=Host(`api.fanflix.${MY_DOMAIN}`)"
      - "traefik.http.routers.simple-fe.entrypoints=websecure"
      - "traefik.http.routers.simple-fe.tls.certresolver=letsencrypt" 


  watchtower:
    image: containrrr/watchtower:latest
    container_name: fanflix_watchtower
    command: --cleanup --include-restarting --label-enable --interval 20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  traefik-global-proxy:
    external: true