version: '3.9'

name: fanflix

services:
  traefik:
    image: traefik:v2.4
    container_name: "fanflix_traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${MY_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  api:
    image: ${DOCKERHUB_USERNAME}/fanflix-api:latest
    container_name: fanflix_api
    ports:
      -  2456:3000
    restart: unless-stopped
    environment:
      DATABASE_USER_NAME: ${DATABASE_USER_NAME}
      DATABASE_HOST_NAME: ${DATABASE_HOST_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_LINK: ${DATABASE_LINK}
      API_SECRET: ${API_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION} 
      NODE_ENV: production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.node-server.rule=Host(`${MY_DOMAIN}`)"
      - "traefik.http.routers.node-server.entrypoints=websecure"
      - "traefik.http.routers.node-server.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"


  watchtower:
    image: containrrr/watchtower:latest
    container_name: fanflix_watchtower
    command: --cleanup --include-restarting --label-enable --interval 20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
